-- Cayo Perico Island IPL Loader
-- Fix untuk tanah tenggelam dan jembatan rusak

CreateThread(function()
    -- CORE ISLAND IPLs (WAJIB!)
    -- IPL utama pulau Cayo Perico
    RequestIpl("h4_islandairstrip")
    RequestIpl("h4_islandairstrip_props")
    RequestIpl("h4_islandx_mansion")
    RequestIpl("h4_islandx_mansion_props")
    RequestIpl("h4_islandx_props")
    RequestIpl("h4_islandxdock")
    RequestIpl("h4_islandxdock_props")
    RequestIpl("h4_islandxdock_props_2")
    RequestIpl("h4_islandxtower")
    RequestIpl("h4_islandx_maindock")
    RequestIpl("h4_islandx_maindock_props")
    RequestIpl("h4_islandx_maindock_props_2")
    RequestIpl("h4_IslandX_Mansion_Vault")
    RequestIpl("h4_islandairstrip_propsb")
    RequestIpl("h4_beach")
    RequestIpl("h4_beach_props")
    RequestIpl("h4_beach_bar_props")
    RequestIpl("h4_islandx_barrack_props")
    RequestIpl("h4_islandx_checkpoint")
    RequestIpl("h4_islandx_checkpoint_props")
    RequestIpl("h4_islandx_Mansion_Office")
    RequestIpl("h4_islandx_Mansion_LockUp_01")
    RequestIpl("h4_islandx_Mansion_LockUp_02")
    RequestIpl("h4_islandx_Mansion_LockUp_03")
    RequestIpl("h4_islandairstrip_hangar_props")
    RequestIpl("h4_IslandX_Mansion_B")
    RequestIpl("h4_islandairstrip_doorsclosed")
    RequestIpl("h4_Underwater_Gate_Closed")
    RequestIpl("h4_mansion_gate_closed")
    RequestIpl("h4_aa_guns")
    RequestIpl("h4_IslandX_Mansion_GuardFence")
    RequestIpl("h4_IslandX_Mansion_Entrance_Fence")
    RequestIpl("h4_IslandX_Mansion_B_Side_Fence")
    RequestIpl("h4_IslandX_Mansion_Lights")
    RequestIpl("h4_islandxcanal_props")
    RequestIpl("h4_beach_props_party")
    RequestIpl("h4_islandX_Terrain_props_06_a")
    RequestIpl("h4_islandX_Terrain_props_06_b")
    RequestIpl("h4_islandX_Terrain_props_06_c")
    RequestIpl("h4_islandX_Terrain_props_05_a")
    RequestIpl("h4_islandX_Terrain_props_05_b")
    RequestIpl("h4_islandX_Terrain_props_05_c")
    RequestIpl("h4_islandX_Terrain_props_05_d")
    RequestIpl("h4_islandX_Terrain_props_05_e")
    RequestIpl("h4_islandX_Terrain_props_05_f")
    RequestIpl("h4_islandx_terrain_01")
    RequestIpl("h4_islandx_terrain_02")
    RequestIpl("h4_islandx_terrain_03")
    RequestIpl("h4_islandx_terrain_04")
    RequestIpl("h4_islandx_terrain_05")
    RequestIpl("h4_islandx_terrain_06")
    RequestIpl("h4_ne_ipl_00")
    RequestIpl("h4_ne_ipl_01")
    RequestIpl("h4_ne_ipl_02")
    RequestIpl("h4_ne_ipl_03")
    RequestIpl("h4_ne_ipl_04")
    RequestIpl("h4_ne_ipl_05")
    RequestIpl("h4_ne_ipl_06")
    RequestIpl("h4_ne_ipl_07")
    RequestIpl("h4_ne_ipl_08")
    RequestIpl("h4_ne_ipl_09")
    RequestIpl("h4_nw_ipl_00")
    RequestIpl("h4_nw_ipl_01")
    RequestIpl("h4_nw_ipl_02")
    RequestIpl("h4_nw_ipl_03")
    RequestIpl("h4_nw_ipl_04")
    RequestIpl("h4_nw_ipl_05")
    RequestIpl("h4_nw_ipl_06")
    RequestIpl("h4_nw_ipl_07")
    RequestIpl("h4_nw_ipl_08")
    RequestIpl("h4_nw_ipl_09")
    RequestIpl("h4_se_ipl_00")
    RequestIpl("h4_se_ipl_01")
    RequestIpl("h4_se_ipl_02")
    RequestIpl("h4_se_ipl_03")
    RequestIpl("h4_se_ipl_04")
    RequestIpl("h4_se_ipl_05")
    RequestIpl("h4_se_ipl_06")
    RequestIpl("h4_se_ipl_07")
    RequestIpl("h4_se_ipl_08")
    RequestIpl("h4_se_ipl_09")
    RequestIpl("h4_sw_ipl_00")
    RequestIpl("h4_sw_ipl_01")
    RequestIpl("h4_sw_ipl_02")
    RequestIpl("h4_sw_ipl_03")
    RequestIpl("h4_sw_ipl_04")
    RequestIpl("h4_sw_ipl_05")
    RequestIpl("h4_sw_ipl_06")
    RequestIpl("h4_sw_ipl_07")
    RequestIpl("h4_sw_ipl_08")
    RequestIpl("h4_sw_ipl_09")
    RequestIpl("h4_islandx_mansion_b")
    RequestIpl("h4_islandxtower_veg")
    RequestIpl("h4_islandx_sea_mines")
    RequestIpl("h4_islandx")
    RequestIpl("h4_islandx_barrack_hatch")
    RequestIpl("h4_islandxdock_water_hatch")
    RequestIpl("h4_beach_party")

    print("^2[Cayo Perico IPL]^7 Semua IPL pulau berhasil dimuat!")
end)

-- Enable/Disable Cayo Perico secara global
CreateThread(function()
    SetIslandEnabled("HeistIsland", true)
    SetScenarioGroupEnabled("Heist_Island_Peds", true)
    SetAudioFlag("LoadMPData", true)
    
    print("^2[Cayo Perico IPL]^7 Pulau Cayo Perico diaktifkan!")
end)

-- Load Minimap untuk Cayo Perico
CreateThread(function()
    local MinimapInfo = {
        -- Koordinat minimap Cayo Perico
        ["ISLANDHOTEL"] = {pos = vector3(4989.18, -5738.45, 19.88), blipColor = 5},
        ["ISLANDAIRSTRIP"] = {pos = vector3(4440.49, -4490.43, 4.24), blipColor = 5},
        ["ISLANDMANSION"] = {pos = vector3(5007.06, -5755.84, 28.85), blipColor = 40},
        ["ISLANDCOMPOUND"] = {pos = vector3(5009.98, -5749.84, 28.48), blipColor = 40}
    }
    
    print("^2[Cayo Perico IPL]^7 Setup minimap selesai!")
end)
